config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls', namespace='transactions')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path

from transactions.views import TransactionsView, CreateTransactionView, CancelTransactionView, ConfirmTransactionView

app_name = 'transactions'

urlpatterns = [
    path('', TransactionsView.as_view(), name='transactions'),
    path('create-transaction/', CreateTransactionView.as_view(), name='create_transaction'),
    path('transaction/<int:pk>/confirm/', ConfirmTransactionView.as_view(), name='confirm_transaction'),
    path('transaction/<int:pk>/cancel/', CancelTransactionView.as_view(), name='cancel_transaction'),
]

users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import SignUpView, LoginUserView

app_name = 'users'

urlpatterns = [
    path('register/', SignUpView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

transactions/models.py
from django.db import models
from django.contrib.auth.models import User


class TransactionStatuses(models.TextChoices):
    PROCESSING = "PROCESSING"
    CANCELED = "CANCELED"
    ACCEPTED = "ACCEPTED"


class Network(models.Model):
    name = models.CharField(
        max_length=25,
        unique=True,
        verbose_name='Blockchain network'
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Network'
        verbose_name_plural = 'Networks'


class Cryptocurrency(models.Model):
    network = models.ForeignKey(
        Network,
        on_delete=models.PROTECT,
        related_name='currencies',
        verbose_name='Blockchain network'
    )
    name = models.CharField(max_length=25, unique=True, verbose_name='Cryptocurrency name')

    def __str__(self) -> str:
        return f'{self.name} | {self.network.name}'

    class Meta:
        verbose_name = 'Cryptocurrency'
        verbose_name_plural = 'Cryptocurrenies'


class ServiceAccount(models.Model):
    user = models.ForeignKey(
        User, 
        on_delete=models.PROTECT, 
        related_name='service_accounts'
    )
    wallet_address = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Wallet Address'
    )
    sub_account_id = models.CharField(
        max_length=10,
        verbose_name='subaccountID'
    )
    network = models.ForeignKey(
        Network,
        on_delete=models.PROTECT,
        related_name='accounts',
        verbose_name='Blockchain network'
    )
    cryptocurrency = models.ForeignKey(
        Cryptocurrency,
        on_delete=models.PROTECT,
        related_name='accounts',
        verbose_name='Cryptocurrency'
    )

    def __str__(self) -> str:
        return f'Service account of {self.user.username} | Network: {self.network.name} | Crypto: {self.cryptocurrency.name}'

    class Meta:
        verbose_name = 'Service Account'
        verbose_name_plural = 'Service Accounts'


class Transaction(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transactions', verbose_name='Sender User')
    sender_address = models.CharField(max_length=255, verbose_name='Sender Wallet Address')
    recipient_address = models.CharField(max_length=255, verbose_name='Recipient Wallet Address')
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Amount')
    status = models.CharField(
        max_length=10,
        default=TransactionStatuses.PROCESSING,
        choices=TransactionStatuses.choices,
        verbose_name='Transaction status'
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Transaction created')

    def __str__(self) -> str:
        return f'Transaction from {self.sender_address} to {self.recipient_address} | amount: {self.amount}'

transactions/forms.py
from django import forms

from .models import Network, ServiceAccount, Transaction


class ServiceAccountAdminForm(forms.ModelForm):

    class Meta:
        model = ServiceAccount
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        network = cleaned_data.get('network')
        cryptocurrency = cleaned_data.get('cryptocurrency').name
        valid_cryptocurrencies = network.currencies.values_list('name', flat=True)
        if cryptocurrency not in valid_cryptocurrencies:
            self.add_error('cryptocurrency', f'{network} has no such currency as {cryptocurrency}')


class TransactionForm(forms.ModelForm):
    sender_address = forms.ModelChoiceField(
        queryset=None,
        label=False,
        empty_label="Select Sender Address",
    )

    class Meta:
        model = Transaction
        fields = '__all__'
        widgets = {
            "sender": forms.HiddenInput(),
            "status": forms.HiddenInput(),
            "recipient_address": forms.TextInput(attrs={
                "placeholder": "Recipient address"
            }),
            "amount": forms.NumberInput(attrs={
                "placeholder": "Amount"
            })
        }
        labels = {
            "recipient_address": False,
            "amount": False,
        }

    def __init__(self, *args, **kwargs):
        sender_address_queryset = kwargs.pop('sender_address_queryset', None)
        super().__init__(*args, **kwargs)
        self.fields['sender_address'].queryset = sender_address_queryset

transactions/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView

from transactions.services.handling_transaction_confirmation_services import send_transaction_confirmation
from transactions.forms import TransactionForm
from transactions.models import TransactionStatuses, Transaction, ServiceAccount


class TransactionsView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    template_name = 'transactions/transactions.html'
    form_class = TransactionForm

    def get(self, request):
        service_accounts = request.user.service_accounts.select_related('network', 'cryptocurrency')
        service_accounts_addresses = service_accounts.values_list('wallet_address', flat=True)

        for_review_transactions = Transaction.objects.filter(
            recipient_address__in=service_accounts_addresses,
            status=TransactionStatuses.PROCESSING
        )

        user_transactions = request.user.transactions.order_by('-created_at')

        form = self.form_class(
            sender_address_queryset=service_accounts,
            initial={"sender": request.user}
        )

        context = {
            "service_accounts": service_accounts,
            "form": form,
            "transactions": user_transactions,
            "transaction_statuses": TransactionStatuses,
            "for_review_transactions": for_review_transactions
        }

        return render(request, self.template_name, context=context)


class CreateTransactionView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('users:login')
    form_class = TransactionForm
    success_url = reverse_lazy('transactions:transactions')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        service_accounts = self.request.user.service_accounts.select_related('network', 'cryptocurrency')
        kwargs['sender_address_queryset'] = service_accounts
        return kwargs

    def form_valid(self, form):
        wallet_address = form.cleaned_data['sender_address'].wallet_address
        recipient_address = form.cleaned_data['recipient_address']

        if wallet_address == recipient_address:
            messages.error(self.request, 'Unable to create a transaction with the same address')
            return redirect(self.get_success_url())

        form.instance.sender_address = wallet_address
        form.save()
        messages.success(self.request, 'Transaction was created successfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Form error. Check inputs')
        return super().form_invalid(form)


class CancelTransactionView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def post(self, request, pk):
        transaction = get_object_or_404(Transaction, pk=pk)
        service_accounts_addresses = request.user.service_accounts.values_list('wallet_address', flat=True)

        if transaction.recipient_address in service_accounts_addresses:
            transaction.status = TransactionStatuses.CANCELED
            transaction.save()
            messages.success(request, 'Transaction was canceled')
        else:
            messages.error(request, 'You have no permission for this')
        return redirect("transactions:transactions")


class ConfirmTransactionView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def post(self, request, pk):
        transaction = get_object_or_404(Transaction, pk=pk)
        service_accounts_addresses = request.user.service_accounts.values_list('wallet_address', flat=True)

        if transaction.recipient_address in service_accounts_addresses:
            confirmation_status: dict = send_transaction_confirmation(
                transaction.sender_address,
                transaction.recipient_address,
                transaction.amount
            )
            if confirmation_status.get("status"):
                transaction.status = TransactionStatuses.ACCEPTED
                transaction.save()

                messages.success(request, 'Transaction was accepted')
            else:
                messages.error(request, 'The transaction was not confirmed')
        else:
            messages.error(request, 'You have no permission for this')

        return redirect("transactions:transactions")

transactions/templates/transactions/transactions.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'transactions/transactions.css' %}">
{% endblock %}
{% block title %} Transactions {% endblock %}

{% block content %}
    <div class="transactions__container">
        <div class="transactions__wrapper">
            <div class="transactions__inner-wrapper">
                <div class="transactions__content-wrapper">
                    <h1>Your transactions list</h1>
                    <div class="line"></div>
                    <div class="transactions__content-inner">
                        {% if transactions %}
                            {% for transaction in transactions %}
                                <div class="service__account-item">
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.sender_address }}</h3>
                                        <p>Sender Address</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.recipient_address }}</h3>
                                        <p>Recipient Address</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.amount }}</h3>
                                        <p>Amount</p>
                                    </div>
                                    <div
                                            class="service__account-item__inner"
                                    >
                                        <h3
                                                {% if transaction.status == transaction_statuses.CANCELED %}
                                                    style="color: red;"
                                                {% elif transaction.status == transaction_statuses.ACCEPTED %}
                                                    style="color: green;"
                                                {% else %}
                                                    style="color: orange;"
                                                {% endif %}
                                        >
                                            {{ transaction.status }}
                                        </h3>
                                        <p>status</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.created_at }}</h3>
                                        <p>Transaction creation date</p>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <h1 style="color: #999999">You don't have Transactions History.....</h1>
                        {% endif %}
                    </div>
                </div>
                <div class="transactions__content-wrapper">
                    <h1>Create Transaction</h1>
                    <div class="line"></div>
                    <form action="{% url 'transactions:create_transaction' %}" method="post" class="transaction__form">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="send_transaction">Send Transaction</button>
                    </form>
                </div>
            </div>
            <div class="transactions__inner-wrapper">
                <div class="transactions__content-wrapper">
                    <h1>Your Service Accounts</h1>
                    <div class="line"></div>
                    <div class="transactions__content-inner">
                        {% if service_accounts %}
                            {% for service_account in service_accounts %}
                                <div class="service__account-item">
                                    <div class="service__account-item__inner">
                                        <h3>{{ service_account.wallet_address }}</h3>
                                        <p>Wallet Address</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ service_account.network.name }}</h3>
                                        <p>Blockchain Network</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ service_account.cryptocurrency.name }}</h3>
                                        <p>Cryptocurrency</p>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <h1 style="color: #999999">You don't have Service Accounts.....</h1>
                        {% endif %}
                    </div>
                </div>
                <div class="transactions__content-wrapper">
                    <h1>Profile</h1>
                    <div class="line"></div>
                    <div class="transactions__content-inner">
                        <p>username: {{ request.user.username }}</p>
                        <p>email: {% if request.user.email %} {{ request.user.email }}  {% else %} You did not enter an email {% endif %}</p>
                        <a href="{% url 'users:logout' %}" class="logout">Logout</a>
                    </div>
                </div>
            </div>
            <div class="transactions__inner-wrapper">
                <div class="transactions__content-wrapper">
                    <h1>Your transactions for review</h1>
                    <div class="line"></div>
                    {% if for_review_transactions %}
                        {% for transaction in for_review_transactions %}
                            <div class="transactions__content-inner">
                                <div class="service__account-item">
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.sender_address }}</h3>
                                        <p>Sender address</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.recipient_address }}</h3>
                                        <p>recipient address</p>
                                    </div>
                                    <div class="service__account-item__inner">
                                        <h3>{{ transaction.amount }}</h3>
                                        <p>amount</p>
                                    </div>
                                    <div class="transaction__review-wrapper">
                                        <form
                                                action="{% url 'transactions:confirm_transaction' transaction.pk %}"
                                                method="post"
                                                class="transaction__review-form"
                                        >
                                            {% csrf_token %}
                                            <button type="submit" class="accept__button">Accept</button>
                                        </form>
                                        <form
                                                action="{% url 'transactions:cancel_transaction' transaction.pk %}"
                                                method="post"
                                                class="transaction__review-form"
                                        >
                                            {% csrf_token %}
                                            <button type="submit" class="cancel__button">Cancel</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>You don't have Transactions for review.....</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}